language: node_js

node_js:
  - "9"
  - "8"
  - "6"

sudo: required
services:
  - docker

script:
  - npm run lint-ci
  - docker-compose up -d mongodb && npm run test-ci
  - docker-compose down

notifications:
  email:
    on_success: never
    on_failure: always
